#### MAC
# virtualenv venv && source ./venv/bin/activate
###WINDOWS
# virtualenv venv && .\venv\Scripts\activate


name: series 
channels:
  - anaconda
  - defaults 
dependencies:
  - ipykernel
  - ipython
  - fs
  - jupyter
  - jupyterlab
  - pathlib 
  - keras
  - pytorch
  - tensorflow
  - pandas-flavor
  - pandas-profiling
  
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pyproj root 
  
  - python = 3.9
  - pip:
    - pyhere
    